# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccruedExpenseInfoDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_year', models.CharField(max_length=10, verbose_name='年份')),
                ('ae_month', models.CharField(max_length=10, verbose_name='月份')),
                ('ae_amount', models.FloatField(max_length=15, verbose_name='预提金额')),
                ('ae_writeoff_amount', models.FloatField(max_length=15, verbose_name='冲销金额')),
                ('ae_order_code', models.CharField(max_length=30, verbose_name='预提订单编号')),
                ('ae_writeoff_order_code', models.CharField(max_length=30, verbose_name='冲销订单编号')),
                ('contract_code', models.CharField(max_length=30, verbose_name='合同编号')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=50, verbose_name='预算项目名称')),
                ('budget_code', models.CharField(max_length=30, unique=True, verbose_name='预算项目编码')),
                ('intensive_code', models.CharField(max_length=30, verbose_name='集约化编码')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('budget_amount', models.FloatField(max_length=15, verbose_name='项目总金额')),
                ('dev_budget', models.FloatField(max_length=15, verbose_name='开发金额')),
                ('mt_budget', models.FloatField(max_length=15, verbose_name='维护金额')),
                ('doc', models.CharField(max_length=100, verbose_name='预算会纪要')),
                ('status', models.CharField(max_length=10, verbose_name='项目状态')),
                ('type', models.CharField(max_length=10, verbose_name='项目类型')),
                ('leader', models.CharField(max_length=10, verbose_name='项目负责人')),
            ],
        ),
        migrations.CreateModel(
            name='ContractInfoDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(max_length=30, verbose_name='预算项目编码')),
                ('contract_name', models.CharField(max_length=100, verbose_name='合同名称')),
                ('contract_code', models.CharField(max_length=30, unique=True, verbose_name='合同编号')),
                ('contract_amount', models.FloatField(max_length=15, verbose_name='合同金额')),
                ('dev_price', models.FloatField(max_length=15, verbose_name='开发单价')),
                ('mt_price', models.FloatField(max_length=15, verbose_name='维护单价')),
                ('dev_workload', models.FloatField(max_length=10, verbose_name='开发人天')),
                ('mt_workload', models.FloatField(max_length=10, verbose_name='维护人天')),
                ('vendor_name', models.CharField(max_length=40, verbose_name='合作商名称')),
                ('vendor_contactor', models.CharField(max_length=10, verbose_name='商务联系人')),
                ('vendor_contactor_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('start_date', models.DateField(verbose_name='合同开始时间')),
                ('end_date', models.DateField(verbose_name='合同结束时间')),
                ('contract_status', models.CharField(max_length=10, verbose_name='合同状态')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_budget_set', to='WorkManageModel.BudgetDO', to_field='budget_code')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfoDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=30, verbose_name='合同编码')),
                ('order_code', models.CharField(max_length=30, verbose_name='订单号')),
                ('order_contract_code', models.CharField(max_length=30, verbose_name='订单合同编码')),
                ('order_amount', models.FloatField(max_length=15, verbose_name='订单金额')),
                ('start_date', models.DateField(verbose_name='结算开始时间')),
                ('end_date', models.DateField(verbose_name='结算结束时间')),
                ('workload_checked', models.IntegerField(verbose_name='是否已核定工作量')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_order_set', to='WorkManageModel.ContractInfoDO', to_field='contract_code')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('fdate', models.DateField(null=True)),
                ('score', models.FloatField(max_length=4)),
                ('age', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='YearBudgetDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(max_length=30, verbose_name='预算项目编码')),
                ('intensive_code', models.CharField(max_length=30, verbose_name='集约化编码')),
                ('year', models.CharField(max_length=10, verbose_name='年度')),
                ('budget_amount', models.FloatField(max_length=15, verbose_name='年度预算金额')),
                ('dev_budget', models.FloatField(max_length=15, verbose_name='年度开发金额')),
                ('mt_budget', models.FloatField(max_length=15, verbose_name='年度维护金额')),
                ('checked_no_order_amount', models.FloatField(max_length=15, verbose_name='已核定未提订单金额')),
                ('unchecked_amount', models.FloatField(max_length=15, verbose_name='已发生未核定金额')),
                ('budget', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='year_budget_set', to='WorkManageModel.BudgetDO', to_field='budget_code')),
            ],
        ),
        migrations.AddField(
            model_name='accruedexpenseinfodo',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_ae_set', to='WorkManageModel.ContractInfoDO', to_field='contract_code'),
        ),
    ]
