# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkManageModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbudgetdo',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_budget_set', to='WorkManageModel.BudgetDO', to_field='budget_code'),
        ),
    ]
